


-- ==========================  USERS  =====================--

DROP DATABASE IF EXISTS uus;
DROP USER IF EXISTS 'UUS'@'localhost';

CREATE USER 'UUS'@'localhost' IDENTIFIED BY 'ITSJUSTATESTDB';

CREATE DATABASE uus;

GRANT ALL PRIVILEGES ON uus.* TO 'UUS'@'localhost';

USE uus;

-- ==========================  SEQUENCES  =====================--

-- CREATE SEQUENCE USER_ID_SEQ START WITH 1050;
-- CREATE SEQUENCE COMPANY_ID_SEQ START WITH 1250;
-- CREATE SEQUENCE FACILITY_ID_SEQ START WITH 10050;
-- CREATE SEQUENCE TASK_ID_SEQ START WITH 1250;
-- CREATE SEQUENCE USER_TASK_ID_SEQ START WITH 71250;
-- CREATE SEQUENCE TIME_SUBMISSION_ID_SEQ START WITH 10050;

-- ==========================  TABLES  =====================--

CREATE TABLE CLIENT (
  ID VARCHAR(64) PRIMARY KEY NOT NULL,
  SECRET VARCHAR(64),
  LOGIN_ID VARCHAR(64) UNIQUE,
  PASSWORD VARCHAR(64),
  REDIRECT_URI VARCHAR(2048),
  EMAIL VARCHAR(128)
);

CREATE TABLE USER (
  INTERNAL_ID BIGINT(16) PRIMARY KEY,
  LOGIN_ID VARCHAR(64) UNIQUE,
  PASSWORD VARCHAR(64),
  EMAIL VARCHAR(128)
);

CREATE TABLE PROFILE (
  USER_INTERNAL_ID BIGINT(16),
  NAME VARCHAR(64),
  JSON LONGBLOB,
  CONSTRAINT COMP_PK_PROFILE PRIMARY KEY (USER_INTERNAL_ID, NAME),
  CONSTRAINT FK_PROFILE_USER FOREIGN KEY (USER_INTERNAL_ID) REFERENCES USER(INTERNAL_ID)
);

-- ==========================  DEFAULTS  =====================--
