
-- ==========================  TABLES  =====================--

CREATE TABLE CLIENT (
  ID VARCHAR(64) PRIMARY KEY NOT NULL,
  SECRET VARCHAR(64),
  LOGIN_ID VARCHAR(64) UNIQUE,
  PASSWORD VARCHAR(64),
  REDIRECT_URI VARCHAR(2048),
  EMAIL VARCHAR(128)
);

CREATE TABLE USER (
  INTERNAL_ID BIGINT(16) PRIMARY KEY,
  LOGIN_ID VARCHAR(64) UNIQUE,
  PASSWORD VARCHAR(64),
  EMAIL VARCHAR(128)
);

CREATE TABLE PROFILE (
  USER_INTERNAL_ID BIGINT(16),
  NAME VARCHAR(64),
  JSON LONGBLOB,
  CONSTRAINT COMP_PK_PROFILE PRIMARY KEY (USER_INTERNAL_ID, NAME),
  CONSTRAINT FK_PROFILE_USER FOREIGN KEY (USER_INTERNAL_ID) REFERENCES USER(INTERNAL_ID)
);
